### ISSUE TITLE
Cache of nodes in Jubaproxy will not  update when failed to register the watcher

### ISSUE THREAD

**Issue by rimms** [jubatus/jubatus#1035]
Jubaproxy use cache of node list.
This cache will updated by the watcher function of ZooKeeper.

Currently, If proxy failed to register the watcher function, proxy will never register this again.

* ``cached_zk::list_`` return ``false``
https://github.com/jubatus/jubatus/blob/0.8.1/jubatus/server/common/cached_zk.cpp#L83
* ``list_cache_[path]`` will be an empty set
https://github.com/jubatus/jubatus/blob/0.8.1/jubatus/server/common/cached_zk.cpp#L52
* Then, ``list_catch_[path]`` will always be found. So, watcher will never be registered.
https://github.com/jubatus/jubatus/blob/0.8.1/jubatus/server/common/cached_zk.cpp#L43

**Comment by kmaehashi** [comment]
Fixed via #1036
