### ISSUE TITLE
Nearest Nneighbor:: type of "ret_num" should be "uint" 

### ISSUE THREAD

**Issue by rimms** [jubatus/jubatus#1042]
https://github.com/jubatus/jubatus/blob/0.8.1/jubatus/server/server/nearest_neighbor.idl#L14

* neighbor_row_from_id(0: string id, 1: **uint** size)
* neighbor_row_from_datum(0: datum query, 1: **uint** size)
* similar_row_from_id(0: string id, 1: **int** ret_num) => I think this type should be **uint**
* similar_row_from_datum(0: datum query, 1: **int** ret_num) => I think this type should be **uint**

**Comment by kmaehashi** [comment]
Fixed via #1049
