### ISSUE TITLE
Providing toolkits to evaluate performance (precision)

### ISSUE THREAD

**Issue by kmaehashi** [jubatus/jubatus#1044]
Providing a feature like cross-validation would be fine.

**Comment by kmaehashi** [comment]
We'll start discussion on this topic, starting with Classifier.

**Comment by kmaehashi** [comment]
### Goal

Provide a toolkit that provides techniques often used by analysts when constructing a ML model

### Requirements and design thoughts

To proivde a toolkit to automatically evaluate a precision, we need an abstraction layers for **Datasets**.
scikit-learn does this using `numpy`; however Jubatus handles not only numbers but `raw` data with types (string, binary).  So we also need to have a abstract layer of **Scheams**.
To handle with multiple data sources, it is also preferable to separate **DataLoader** layer.

### Example code

Prototype implementation is here: https://github.com/kmaehashi/jubakit

```
from jubakit import DataLoader
from jubakit.classifier import Schema, Dataset, Classifier

# DataLoader: reads data source from various kinds, including csv, json, odbc, twitter, MQ, etc.
# and returns each row in key-value format.
loader = DataLoader.csv('sample_file.csv')

# Schema: defines the key and its type.
schema = Schema({
  'is_spam': Schema.LABEL,
  'message': Schema.STRING,
})

# Dataset: bind the loader with the schema.
dataset = Dataset(loader, schema)

# Client: create classifier.
classifier = Classifier('127.0.0.1', 9199, '')

# Now train the classifier with the dataset.
for e in classifier.train(dataset):
  # show training result
  print e

# Run the cross validation with the dataset.
# The results are automatically summarized and reported.
print classifier.cross_validation('kfold', n=4)
print classifier.cross_validation('label_kfold')
```

**Comment by shiodat** [comment]
The prototype implementation looks good to me！

In addition, I want some **Metrics** to evaluate the results.
Scikit-learn provides 18 metrics to evaluate the classifier results but Jubatus doesn't have.
http://scikit-learn.org/stable/modules/model_evaluation.html#classification-metrics

In my opinion, f1_score, precision, recall and AUC metrics are useful.

**Comment by yukimori** [comment]
I with to add dataset generation API like scikit-learn dataset API(http://scikit-learn.org/stable/datasets/) for this toolkit.

**Comment by kmaehashi** [comment]
Implemented in https://github.com/jubatus/jubakit/pull/1
