### ISSUE TITLE
proposal of adding "default" configuration file

### ISSUE THREAD

**Issue by kmaehashi** [jubatus/jubatus#1117]
Currently we provide many [example config files](https://github.com/jubatus/jubatus/tree/master/config/), however beginners cannot tell where to start with.  I propose adding config named `default.json` for each engine, which is "good" for "general" use cases.

I suppose that the following configurations can be recommended for the first try, even without prior knowledge of use cases and problem settings:

* All engines using Datum: bigram enabled by default for all string features
* classifier: AROW, regularization_weight: 1.0
* recommender: inverted_index
* anomaly: lof + inverted_index_euclid + ignore_kth_same_point

etc...

**Comment by kumagi** [comment]
:+1:

**Comment by kmaehashi** [comment]
Fixed via #1120
