### ISSUE TITLE
"-ldl" link problem in Linux

### ISSUE THREAD

**Issue by kazuki** [jubatus/jubatus#1121]
以下のエラーが出てリンクに失敗します
```
jubatus/server/fv_converter/libjubaserv_fv_converter.so: error: undefined reference to 'dlclose'
jubatus/server/fv_converter/libjubaserv_fv_converter.so: error: undefined reference to 'dlerror'
jubatus/server/fv_converter/libjubaserv_fv_converter.so: error: undefined reference to 'dlsym'
jubatus/server/fv_converter/libjubaserv_fv_converter.so: error: undefined reference to 'dlopen'
```

以下のプルリクの変更により，wafのDLが設定されなくなりました．
https://github.com/jubatus/jubatus/pull/1099/files#diff-dc6134e3d3c869a052520d86f46371dcL83
その結果，以下のwscriptのuseにてDLを参照しているにも関わらず，
DLが設定されていないので，リンクの設定が正しくなされなくなったものと思われます．
https://github.com/jubatus/jubatus/blob/master/jubatus/server/fv_converter/wscript#L32

0.9.0のバイナリパッケージには libdl へのリンクが含まれているのですが，
Gentoo上でのビルド時に上記問題が発生しました．
もしかしたらディストリ依存かもしれませんが，上記の原因を見る限りだと
`conf.check_cxx(lib = 'dl')` は必要だと思います．

**Comment by kmaehashi** [comment]
ありがとうございます。RHEL 6/7, Ubuntu 12/14 では問題なかったので、ディストリ依存のようです。
https://github.com/jubatus/jubatus/pull/1122 の通り修正します。

**Comment by kmaehashi** [comment]
@kazuki develop ブランチに修正をマージしたので、念のため問題ないかどうか確認していただいてもよろしいですか？

**Comment by kazuki** [comment]
@kmaehashi 直っていることを確認しました．ありがとうございました．
