### ISSUE TITLE
Preserve old DEB packages on Packages.gz

### ISSUE THREAD

**Issue by miyakawataku** [jubatus/jubatus#1125]
Package.gz (http://download.jubat.us/apt/binary/Packages.gz) now lists only the current newest version 0.9.1-1, whereas there are still older package files (0.8.9-1, 0.9.0-1) on the server (http://download.jubat.us/apt/binary/pool/).

As a result, install scripts which specifies the old versions are now broken.

I think it is better to preserve old packages on the list for an appropriate period of time, for stabilizing installation.

**Comment by kmaehashi** [comment]
Thank you for pointing this out.  We are currently working on it.

**Comment by kmaehashi** [comment]
The issue should now be resolved.  @miyakawataku Could you please confirm?

**Comment by miyakawataku** [comment]
@kmaehashi I could install the old packages. Thanks!

**Comment by kmaehashi** [comment]
Thanks! :smile:
