### ISSUE TITLE
validate save/load RPC argument

### ISSUE THREAD

**Issue by kmaehashi** [jubatus/jubatus#1188]
Currently `save`/`load` RPC does not perform any validation on the `id` argument.
It is better to white-list the parameter to avoid unexpected error.

http://jubat.us/en/api/common_structs.html#save__s

I have two ideas:

1. "loose" rule ... any signs and alphanumeric characters excluding slash (`/`), or more specifically: 0x20-0x7e, excluding 0x2f
2. "strict" rule ... `[a-zA-Z0-9_]`

**Comment by kmaehashi** [comment]
We decided to go with idea 1.

**Comment by rimms** [comment]
Fixed via https://github.com/jubatus/jubatus/pull/1192
