### ISSUE TITLE
Performance regression in classifier since commit 26362610

### ISSUE THREAD

**Issue by kazuki** [jubatus/jubatus#1190]
I think local_mixture is 2x slower than local storage.

I measured performance in classifier train method through embedded_jubatus.

20news train time:
* local storage: 35s
* local_mixture storage: 52s

In commit 26362610, always uses local_mixture storage instead of local storage in standalone mode.
This causes performance regression in standalone classifier/regression.

(local_mixture's set method calls lookup in two times more than local storage)
https://github.com/jubatus/jubatus_core/blob/master/jubatus/core/storage/local_storage.cpp#L141
https://github.com/jubatus/jubatus_core/blob/master/jubatus/core/storage/local_storage_mixture.cpp#L179-L180

**Comment by kmaehashi** [comment]
Thank you for reporting the issue.
Maybe we can resolve the issue by changing local_storage serialization format to the same format as local_storage_mixture and reverting https://github.com/jubatus/jubatus/commit/26362610725c42190b7dbcd2fb3377d467424fee.

**Comment by shiodat** [comment]
Fixed via https://github.com/jubatus/jubatus/pull/1193, https://github.com/jubatus/jubatus_core/pull/359 and https://github.com/jubatus/embedded-jubatus-python/pull/32.

**Comment by kmaehashi** [comment]
Refs #1153
