### ISSUE TITLE
Improve get_status of anomaly

### ISSUE THREAD

**Issue by rimms** [jubatus/jubatus#1194]
This issue is a part of #633 .

``jubaanomaly::get_status()`` returns only the type of storage like ``{"storage": "lof"}``.

I picked up some useful metrics of ``jubaanomaly``.

How about my idea?

* lof and light_lof
  * ``max_id``: current max value of id in storage (useful to understand next id)
  * ``num_ignored``: the number of ids that were ignored by ``ignore_kth_same_point`` 
  * unlearner's status: See https://github.com/jubatus/jubatus_core/pull/166
* lof
  * ``num_id_master``: number of ids in ``lof_storage::_lof_table``
  * ``num_id_diff``: number of ids in ``lof_storage::_lof_table_diff``
* light_lof
  * ``num_id``: number of ids (we can get this via ``len(get_all_ids())``)

**Comment by kmaehashi** [comment]
Fixed via PRs above.
