### ISSUE TITLE
plugin: what is the output of ORB image plugin?

### ISSUE THREAD

**Issue by TkrUdagawa** [jubatus/jubatus#1196]
The ORB of image_plugin makes tupple feature like (key#algorithm/i-j-p, p)
https://github.com/jubatus/jubatus/blob/master/plugin/src/fv_converter/image_feature.cpp#L121-L124

What do these i, j and p mean?
And p is used as key and value. Is it correct?

I think we need to rethink the output of ORB.

**Comment by imaimai1125** [comment]
I fixed the output of ORB as following.

**Comment by imaimai1125** [comment]
According to the algorithm of ORB, it returns 256-dimensional bit vectors at each keypoints.
Thus, I fixed the output of ORB via #1201 as following.

`key#ORB/i-j, p_bit`
- i : keypoints
- j : element of bit vector
- p_bit : value (0 or 1)

**Comment by kmaehashi** [comment]
Fixed via #1201
