### ISSUE TITLE
404 not found http://download.jubat.us/apt/ubuntu/xenial/binary/Packages

### ISSUE THREAD

**Issue by t-umeno** [jubatus/jubatus#1227]
404 not found http://download.jubat.us/apt/ubuntu/xenial/binary/Packages

Please check jubatus website.

**Comment by rimms** [comment]
We fixed via https://github.com/jubatus/jubatus-package/pull/2

@t-umeno Would you try again, please?

**Comment by t-umeno** [comment]
No problem. Thank you!

~$ env LANG=C sudo apt-get update && env LANG=C sudo apt-get dist-upgrade

(snip)
Ign:6 http://download.jubat.us/apt/ubuntu/xenial binary/
InRelease
Get:8 http://download.jubat.us/apt/ubuntu/xenial binary/ Release [789
B]
Ign:9 http://download.jubat.us/apt/ubuntu/xenial binary/ Release.gpg
Ign:10 http://download.jubat.us/apt/ubuntu/xenial binary/
Packages.diff/Index
Ign:11 http://download.jubat.us/apt/ubuntu/xenial binary/
Translation-en
Ign:12 http://download.jubat.us/apt/ubuntu/xenial binary/
Translation-ja
Ign:11 http://download.jubat.us/apt/ubuntu/xenial binary/
Translation-en
Ign:12 http://download.jubat.us/apt/ubuntu/xenial binary/
Translation-ja
Ign:11 http://download.jubat.us/apt/ubuntu/xenial binary/
Translation-en
Ign:12 http://download.jubat.us/apt/ubuntu/xenial binary/
Translation-ja
Ign:11 http://download.jubat.us/apt/ubuntu/xenial binary/
Translation-en
Ign:12 http://download.jubat.us/apt/ubuntu/xenial binary/
Translation-ja
Ign:11 http://download.jubat.us/apt/ubuntu/xenial binary/
Translation-en
Ign:12 http://download.jubat.us/apt/ubuntu/xenial binary/
Translation-ja
Ign:11 http://download.jubat.us/apt/ubuntu/xenial binary/
Translation-en
Ign:12 http://download.jubat.us/apt/ubuntu/xenial binary/
Translation-ja
W: The repository 'http://download.jubat.us/apt/ubuntu/xenial binary/
Release' is not signed.
(snip)




2018-04-02 11:41 GMT+09:00 IMAMASU Ryohei <notifications@github.com>:

**Comment by rimms** [comment]
Thanks!
