### ISSUE TITLE
Use of angle brackets around file names for include statements

### ISSUE THREAD

**Issue by elfring** [jubatus/jubatus#1233]
Would you like to [replace any double quotes](https://github.com/jubatus/jubatus/blob/cc8d7ca9e638bd1513ca2b95afead7e8db54d996/jubatus/server/framework.hpp#L21 "Check inclusion style") by [angle brackets around file names for include statements](https://stackoverflow.com/questions/21593/what-is-the-difference-between-include-filename-and-include-filename "What is the difference between #include <filename> and #include “filename”?")?

**Comment by rimms** [comment]
@elfring Thank you for your report. 👍
