### ISSUE TITLE
Remove an unnecessary null pointer check

### ISSUE THREAD

**Issue by elfring** [jubatus/jubatus#1234]
[An extra null pointer check is not needed](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") in [the destructor for the class “rpc_mclient”](https://github.com/jubatus/jubatus/blob/0cf562461ee1bb04d4ffdd3c101612c5885a3f8e/jubatus/server/common/mprpc/rpc_mclient.hpp#L129 "Update candidate: Destructor for rpc_mclient").

**Comment by rimms** [comment]
@elfring Thank you for your report. 👍
