### ISSUE TITLE
Which algorithms aren't sensitive to feature scaling?

### ISSUE THREAD

**Issue by deklanw** [jubatus/jubatus#1240]
Since dynamic normalization isn't supported according to, 
https://github.com/jubatus/jubatus/issues/255#issuecomment-56336693

Which algorithms aren't sensitive to feature scaling? 

I'm particularly interested in classification, but for documentation, it would be nice to know for each algorithm. Some applications aren't amenable to static feature scaling: min/max change or avg/std change.

**Comment by shiodat** [comment]
Sorry for late reply.

Jubatus has two types of classification algorithms, linear classifiers and nearest neighbor classifiers.
Unfortunately, most of them are sensitive to feature scaling.

- Almost all Linear classifers use weight regularization techniques and they are affected by the feature scaling. `perceptron` and `PA` does not use regularization but they usually perform poorly.

- Nearest neighbor classifiers have two distance metrics, euclidean one and cosine one. Both of them are sensitive to feature scaling.

If you want to use Jubatus classifiers, please calculate the feature stats and apply feature scaling: min/max scaling, standard scaling, and so on.

Jubatus supports min/max scaling. You specify  `min` and `max` values of features and it works.
- Official document: http://jubat.us/en/fv_convert.html?highlight=min#num-filter-types
- Config file example: https://github.com/jubatus/jubatus-example/blob/master/winequality/config.json
