### ISSUE TITLE
recommender: clear_row don't free acquired resources

### ISSUE THREAD

**Issue by rimms** [jubatus/jubatus#294]
I tried to measure memory size on before and after call `clear_row`.

The result is following. The value is `RSS` size which got by using `get_status`.

method         | after start-up | after update_row 100K ID | after clear_row 10K ID
---------------|----------------|--------------------------|-----------------------
lsh            | 4312           | 521888                   | 522048
minhash        | 4308           | 216708                   | 216840
euclid_lsh     | 4336           | 236324                   | 236672
inverted_index | 4292           | 434044                   | 434192

We cannot use jubarecommender long time without some solution (e.g. stop service and add memory ...).

**Comment by kmaehashi** [comment]
As we think this behavior is by-design, we close this issue.
