### ISSUE TITLE
Model compatibility in classifiers

### ISSUE THREAD

**Issue by unnonouno** [jubatus/jubatus#469]
Classifier models for stand alone mode are incompatible with models for distributed mode. It is because they use different storage classes, `local_storage` and `local_storage_mixture`.

**Comment by kmaehashi** [comment]
@kumagi We still need to work on this. Any concerns?  Change the milestone / assignee if needed.

**Comment by kumagi** [comment]
This problem should be solved with import/export problem.
https://github.com/jubatus/jubatus/issues/640 
I expect that @gintenlabo will solve it.

**Comment by kmaehashi** [comment]
Fixed via #1153
