### ISSUE TITLE
automation of model backup

### ISSUE THREAD

**Issue by kmaehashi** [jubatus/jubatus#562]
I'm currently trying to automate the model backup. So far I need these steps:

1. Issue `save` method to the server.
2. Issue `get_status` method to get the server ID (like `192.168.0.1_19199`) and datadir (like `/tmp`).
3. Construct file path by concatenating them all (`/tmp/192.168.0.1_19199_jubatus_modelname.js`).
4. Finally, scp over from the server.

So messy :(

Isn't it nice to return the tuple of server ID and saved file path as a result of `save` method?
Proxy can aggregate them like `get_status` method, even in distributed environment.

**Comment by gintenlabo** [comment]
Fixed via https://github.com/jubatus/jubatus/issues/971.
