### ISSUE TITLE
Proxy does not return unified value

### ISSUE THREAD

**Issue by rimms** [jubatus/jubatus#586]
I tested the aggregation process of Jubatus Proxy with `save` method.

* Jubatus Cleint: `timeout` = 300 sec
* `jubaclassifier_proxy`: `interconnect timeout` = 10 sec

In the following case, Jubatus Proxy returned `true` to Client.
```
Client ----> Proxy --+-- OK --> Server1
                     |
                     +-- TO --> Server2

 * OK: Success (Return "true")
 * TO: Request Timeout
```

In the following case, Jubatus Proxy returned `MessagePack::RPC::RuntimeError: request timed out` to Client.
```
Client ----> Proxy --+-- OK --> Server1
                     |
                     +-- OK --> Server2
                     |
                     +-- TO --> Server3

 * OK: Success (Return "true")
 * TO: Request Timeout
```

This behavior is very confusing.
And, I think user will not be able to handle the error correctly.

I believe we should discuss about how to return error from Jubatus Proxy.

**Comment by rimms** [comment]
Discussion on 2015-2-09:
* https://gist.github.com/rimms/c30548fa60113474633d

**Comment by kmaehashi** [comment]
@rimms Please raise a new issue to implement this and close this issue.

**Comment by rimms** [comment]
I raised #985 to implement this.
