### ISSUE TITLE
lof and light_lof does not have common API to update rows

### ISSUE THREAD

**Issue by beam2d** [jubatus/jubatus#588]
``lof`` does not support ``overwrite``, while ``light_lof`` does not support ``update``. It is problematic when user wants to write generic client codes using ``lof`` and ``light_lof``.

**Comment by hido** [comment]
I would also like to propose to solve this issue in 0.7.0 since it involves API change.

**Comment by kmaehashi** [comment]
Fixed via https://github.com/jubatus/jubatus_core/pull/154
