### ISSUE TITLE
Add more information about state of model to get_status

### ISSUE THREAD

**Issue by rimms** [jubatus/jubatus#633]
Currently, `jubaclassifier` returns following values through `get_status`:
- `storage`: Name of storage class
- `num_classes`: Number of classes (labels)
- `num_features`: Number of features
- `diff_size`: Number of features in diff (unmixed data) <Only distributed mode>

These are very useful to know the state of model.

But, `jubaanomaly` returns only `storage` like `"storage" => "lof"`.

I think we need following steps to solve this issue:
- Decide the spec
- Implement this spec

Our first goal is to decide the effective metrics information of each engine

**Comment by kmaehashi** [comment]
@rimms Please delegate this issue to @gintenlabo.

**Comment by kmaehashi** [comment]
We did the following improvements for 0.8.1:

* classifier: https://github.com/jubatus/jubatus_core/pull/166
* linear_mixer: https://github.com/jubatus/jubatus/pull/1030

We should do this for other engines too.

**Comment by kmaehashi** [comment]
Let's complete this task around 1.0.6 (estimated on Oct 2017)

**Comment by kmaehashi** [comment]
@rimms Please create child issues.
