### ISSUE TITLE
Support import/export for model compatibility between different environments

### ISSUE THREAD

**Issue by hido** [jubatus/jubatus#640]
Current save/load operations support the model reusability only on the same environment where the models are built.
On the other hand, users might want to use the models on another environment.
Since the saved models are lack of some information to reconstruct the model, especially about what only zookeeper knows but servers doesn't.

For that purpose, we may make save/load more self-contained and compatible for running on the other environments, or, create new interface such as import/export to support such functionalities.

**Comment by kmaehashi** [comment]
Refs https://github.com/jubatus/jubatus_core/pull/131

**Comment by kmaehashi** [comment]
@TkrUdagawa Please list up the requirements.
