### ISSUE TITLE
Push-Mixer does not work in NNBased-Recommender 

### ISSUE THREAD

**Issue by rimms** [jubatus/jubatus#644]
When running NNBased-Recommender, specifying ``--mixer skip_mixer`` will failed to MIX.

```
W0203 18:02:52.974720 21170 push_mixer.cpp:296] unsupported method (get_pull_argument_impl) : mix failed
```

Some mixables which are used in NNBased-Recommender do not support `get_pull_argument`, `push` and `pull`.
* [jubatus/core/recommender/nearest_neighbor_recommender.cpp#L80](https://github.com/jubatus/jubatus/blob/87e84c2844ee7ac738fe67ac8396c0c8d96b8ce5/jubatus/core/recommender/nearest_neighbor_recommender.cpp#L80)
* [jubatus/core/driver/recommender.cpp#L52](https://github.com/jubatus/jubatus/blob/37c57d982c2d91f4a72bcbb8f2dc1f2a1c9b3e2d/jubatus/core/driver/recommender.cpp#L52)

**Comment by kmaehashi** [comment]
I think this problem is now resolved by the refactoring done in core/server separation.
