### ISSUE TITLE
durability for regression

### ISSUE THREAD

**Issue by kumagi** [jubatus/jubatus#648]
now, classifier get a durability for machine failure.
the same mechanism is needed for regression too.

**Comment by kumagi** [comment]
does regression use `simple_storage` ?
if so, durability is inherited from `classifier`?

**Comment by kmaehashi** [comment]
@kumagi As commented in https://github.com/jubatus/jubatus/issues/648#issuecomment-84804884, this issue may be already fixed?  If so, please close this issue.

**Comment by kmaehashi** [comment]
I confirmed that this feature is already implemented for regression too.
When a new server tries to join to the existing cluster, the model is automatically copied from existing server.

```
2015-06-09 13:03:19,465 17317 INFO  [linear_mixer.cpp:395] start to get model from other server
2015-06-09 13:03:19,467 17202 INFO  [linear_mixer.cpp:571] sending learning-model. size = 191
```

**Comment by kmaehashi** [comment]
Cleared milestone.
