### ISSUE TITLE
Clustering: segfault when get_nearest_center is called before MIX

### ISSUE THREAD

**Issue by kmaehashi** [jubatus/jubatus#667]
Discussion from https://github.com/jubatus/jubatus/pull/650#issuecomment-34601967

**Comment by rimms** [comment]
I confirmed that segfault doesn't occur when ``get_nearest_center`` is called before MIX.
An exception "clustering is not performed yet" was raised.

This problem is fixed via https://github.com/jubatus/jubatus_core/issues/150 and https://github.com/jubatus/jubatus_core/pull/95.
