### ISSUE TITLE
Add image extraction plug-in by default

### ISSUE THREAD

**Issue by kmaehashi** [jubatus/jubatus#843]
Adding image extraction plugin by default will be a great help for users who is trying to handle binary data on Jubatus.

https://github.com/unnonouno/jubatus-image-sample

To keep library dependency minimum, I think it's better not to build the plugin by default; only be built when ``./waf configure --enable-opencv`` is given, for example.

**Comment by kmaehashi** [comment]
Discussion in 2016-10-03:
* We are going to provide a separate binary package that provides opencv plugin, to separate opencv dependency from main package.

**Comment by zdjordje123** [comment]
Dear Mr. Maehashi,


  I do apologize for sending email to this address. I need some clarifications. Perhaps you could point nme to proper answers.

  The question is very short: Why would a developer or an organization use Jubatus rather than Spark 2.0? What advantages does Jubatus brings to the table?


  I would appreciate a link to a white paper or article providing answers.


Thank you in advance

Zoran Djordjevic

________________________________

**Comment by kmaehashi** [comment]
@zdjordje123 Although Jubatus and Spark are both distributed data processing system, they cannot be compared directly.  Spark is a generic batch data processing platform bulit on top of Hadoop; Jubatus focuses on real-time machine learning.  See the Jubatus Overview page for details.  http://jubat.us/en/overview.html

**Comment by zdjordje123** [comment]
Thank you for your prompt response. Jubatus Overview page compares Jubatus with Hadoop and Mahout. It does not discuss relationship to or benefits of Jubatus when compared to Spark 2.0 Streaming.  In Spark 2.0,  Streaming could be used to build fairly powerful real-time processing system. It also provides the benefits of a popular and very versatile API.

**Comment by kmaehashi** [comment]
@zdjordje123 As [Spark Streaming Overview](http://spark.apache.org/docs/latest/streaming-programming-guide.html#overview) says, Spark Streaming splits records in a stream into batches (sets of records) and processes each batch in Spark engine.  Jubatus, on the other hand, directly handles each records in a stream, so machine learning results (e.g., classified label) for each records can be retrieved in very low latency.

If you need further discussion, could you please use other channel like Google Groups? (https://groups.google.com/forum/#!forum/jubatus)
This discussion is unrelated to the issue.

**Comment by kmaehashi** [comment]
Fixed via #843
