### ISSUE TITLE
classifier: Is it intentional to use @random for set_label?

### ISSUE THREAD

**Issue by kmaehashi** [jubatus/jubatus#850]
``delete_label`` is marked as ``@broadcast``, whereas ``set_label`` is marked as ``@random``.  Is this an expected behavior?

https://github.com/jubatus/jubatus/blob/0.6.1/jubatus/server/server/classifier.idl#L74

**Comment by kmaehashi** [comment]
Labels added via `set_label` (labels without feature vectors) will not be propagated via MIX.
We may have two options:

* Change `set_label` to `@broadcast`.
* Change `get_diff` / `put_diff` to support propagation of labels without fv. (I think this idea is high development cost & low benefit)

**Comment by kmaehashi** [comment]
>    Change set_label to @broadcast.

We decided to go with this idea, as the latter idea is cost inefficient.

**Comment by rimms** [comment]
Fixed via #979
