### ISSUE TITLE
"get_status" and "get_diff" don't work in parallel

### ISSUE THREAD

**Issue by rimms** [jubatus/jubatus#912]
I believe``get_status`` and ``get_diff`` should work in parallel.
Because, ``get_status`` and ``get_diff`` don't update the resources of jubatus.

I think we should remove the ``scoped_lock`` below.
https://github.com/jubatus/jubatus/blob/0.6.6/jubatus/server/framework/mixer/linear_mixer.cpp#L347 
https://github.com/jubatus/jubatus/blob/0.6.6/jubatus/server/framework/mixer/linear_mixer.cpp#L538

**Comment by rimms** [comment]
Sorry, I mistook the first report.
I updated title and comment.

**Comment by kmaehashi** [comment]
Discussion from today's meeting:
Remove this line.
https://github.com/jubatus/jubatus/blob/0.6.6/jubatus/server/framework/mixer/linear_mixer.cpp#L347

**Comment by rimms** [comment]
Fixed via #941
