### ISSUE TITLE
Support sequential data

### ISSUE THREAD

**Issue by unnonouno** [jubatus/jubatus#93]
`fv_converter` does not support sequential data. Users need to use abnormal ways when they use features from sequential data such as frequencies of data sequence extracted with FFT. I have four ideas to treat sequential data with the current Jubatus:

- Serialize sequences in strings and store them to `string_values`
- Add a mutable queue to `num_feature`, and store histories of inputs
- Make a queue in clients
- Hack `fv_converter` ;-p

Of course these hacks are not smart. More natural support is desirable.

**Comment by kmaehashi** [comment]
As we now have JubaQL (for production) and jubakit (for small environments and experiments) which can process sequential data.
