### ISSUE TITLE
RPM package need more clear version dependency

### ISSUE THREAD

**Issue by kmaehashi** [jubatus/jubatus#933]
Currently RPM package does not declare version dependency.
This may cause mismatch of package versions, e.g., installing jubadump-0.6.6 and jubatus-0.7.0 at the same time is currently possible.

**Comment by kmaehashi** [comment]
I'll do some improvement on packaging tool to support RHEL 7, so I'll resolve this issue at the same time.

**Comment by rimms** [comment]
FIxed via #1001
