### ISSUE TITLE
Eliminate LD_LIBRARY_PATH from profile files.

### ISSUE THREAD

**Issue by gwtnb** [jubatus/jubatus#943]
http://xahlee.info/UnixResource_dir/_/ldpath.html
http://stackoverflow.com/questions/25918462/why-ld-library-path-is-bad-and-the-correct-way-to-load-dynamic-libraries

https://github.com/jubatus/jubatus/blob/0.7.0/tools/packaging/allinone/jubapkg#L272
https://github.com/jubatus/jubatus/blob/0.7.0/tools/packaging/allinone/jubapkg#L282
https://github.com/jubatus/jubatus-installer/blob/0.7.0/install.sh#L293

**Comment by kmaehashi** [comment]
As this issue is blocked by #892, we'll change the milestone back to Near Future.
