### ISSUE TITLE
Move to C++11.

### ISSUE THREAD

**Issue by gwtnb** [jubatus/jubatus#945]
Move to C++11 for productivity.

**Comment by kmaehashi** [comment]
In the discussion of the meeting on 2015-03-02, we decided to set the milestone to Pending.

Our support OS includes RHEL 6, which does not provide C++11 compiler by default.
We may use Red Hat Developer Tools, which is a paid add-on to RHEL that includes g++4.8.
However, not every system have RHDT contract; it is difficult to troubleshoot issues (especially segv etc.) without toolchains that support C++11.

**Comment by kazuki** [comment]
I agree to this proposal with following reasons.

- To upgrade msgpack-c library, C++11 is required (msgpack-c C++03 tuple implementation has compatibility issue). If continued to use the old version, conflicts msgpack-c version in future or in some linux distribution.
- I am working to improve NN performance (https://github.com/jubatus/jubatus_core/issues/244). Next step is parallel searching. In https://github.com/jubatus/jubatus_core/tree/feature/parallel_search_nn branch, uses own threadpool implementation. c++11 introduced std::async(http://en.cppreference.com/w/cpp/thread/async). I want to use that feature to implement parallel search, to more simply and smaller code size.
