### ISSUE TITLE
verbose mode is required

### ISSUE THREAD

**Issue by kumagi** [jubatus/jubatus#947]
Now jubatus runs without logging for all RPC(except save/load).
It is uncomfortable for beginner who can't assert weather RPC is correctly called or not.

Jubatus should log all rpc called when required.
Yes, it will be impact for performance seriously. It is feature for debug.

**Comment by kmaehashi** [comment]
Discussion on 2016-07-04:

* We plan to change the behavior `DEBUG` logs; DEBUG logs will be able to be printed without recompiling (--enable-debug) jubatus.

**Comment by kmaehashi** [comment]
Fixed via #1143
