### ISSUE TITLE
nearest_neighbor uses random distribution strategy for {similar,neighbor}_row_from_id

### ISSUE THREAD

**Issue by kmaehashi** [jubatus/jubatus#950]
In NN, `set_row` method uses `cht` distribution strategy to distribute by the row ID.
However, `{similar,neighbor}_row_from_id` methods use `random` distribution strategy.

I think this may cause `{similar,neighbor}_row_from_id` to return a bit out-dated result until the data added via `set_row` is propagated via MIX.

**Comment by kumagi** [comment]
I think, it may be good to remain `similar_row` with `random`.

**Comment by kmaehashi** [comment]
Discussion in the meeting on 2015-03-16:
* As @kumagi noted, it is assumed that there is a bias to the access frequency (i.e., some IDs are much likely to be accessed frequently than the rest).  We use `#@random` to equally disrtibute the workload in such case.
* Jubatus' distribution strategy gurantees that the model data will be shared after MIX.  Using `#@random` does not break this rule.
* We set the milestone to Pending for further discussion.

**Comment by kmaehashi** [comment]
I think it is OK to close this issue.
