### ISSUE TITLE
Stop printing 'Done processing...' in cpplint.

### ISSUE THREAD

**Issue by gwtnb** [jubatus/jubatus#951]
Many 'Done processing...' lines are noisy, so they should be printed only when they are required explicitly (--verbose?).
https://github.com/jubatus/jubatus/blob/master/tools/codestyle/cpplint/cpplint.py#L3297

**Comment by kumagi** [comment]
I think that line should be removed.
`--verbose` option will never be used, if we implement it.

**Comment by kmaehashi** [comment]
`cpplint.py` is still well-maintained, so contributing to the upstream is worth considering.

https://code.google.com/p/google-styleguide/source/list?path=/trunk/cpplint/cpplint.py

**Comment by kmaehashi** [comment]
add grep to wscript code.

**Comment by kumagi** [comment]
Let's resolve with `$ grep -v`

**Comment by kmaehashi** [comment]
I did this because I just need this :)

https://github.com/jubatus/jubatus_core/commit/d7c11fe1e525ac596aed1c8276668f1a886c2924

**Comment by gwtnb** [comment]
jubatus (not jubatus_core) also has cpplint and it should be fixed. https://github.com/jubatus/jubatus/blob/master/wscript#L184

**Comment by kmaehashi** [comment]
Thanks! Fixed via https://github.com/jubatus/jubatus/pull/964.
