### ISSUE TITLE
Stop MIX when MIX protocol version mismatch detected

### ISSUE THREAD

**Issue by rimms** [jubatus/jubatus#955]
Currently, Jubatus Server is going to shutdown when MIX protocol version mismatch detected.
https://github.com/jubatus/jubatus/blob/0.7.0/jubatus/server/framework/mixer/linear_mixer.cpp#L586

But, MIX is executed.
https://github.com/jubatus/jubatus/blob/0.7.0/jubatus/server/framework/mixer/linear_mixer.cpp#L398-L399

**Comment by kmaehashi** [comment]
Fixed via #961.
