### ISSUE TITLE
Does not exit on SIGTERM in corner cases

### ISSUE THREAD

**Issue by kmaehashi** [jubatus/jubatus#956]
There is a time gap between starting sigwait thread and registering signal callback function.
Signals must be masked before registering callback function, otherwise the server does not stop even after receiving SIGTERM in corner cases.

For server, sigwait thread is started at https://github.com/jubatus/jubatus/blob/0.7.0/jubatus/server/framework/server_helper.cpp#L49 and SIGTERM hander is registered at https://github.com/jubatus/jubatus/blob/0.7.0/jubatus/server/framework/server_helper.hpp#L233 .

For proxy, sigwait thread is started at https://github.com/jubatus/jubatus/blob/0.7.0/jubatus/server/framework/proxy_common.cpp#L60 and SIGTERM handler is registered at https://github.com/jubatus/jubatus/blob/0.7.0/jubatus/server/framework/proxy.cpp#L89 .

**Comment by gintenlabo** [comment]
fixed via https://github.com/jubatus/jubatus/issues/966.
