### ISSUE TITLE
Calling push_cleanup should be done in one place

### ISSUE THREAD

**Issue by kmaehashi** [jubatus/jubatus#967]
We want to invoke `kill(getpid(), SIGTERM)` when ZK session expired or session recovery timed out.
This callback is currently registered twice:

* https://github.com/jubatus/jubatus/blob/0.7.0/jubatus/server/common/membership.cpp#L114
* https://github.com/jubatus/jubatus/blob/0.7.0/jubatus/server/common/membership.cpp#L212

Registering callback function should be done in one place, for example in here:
https://github.com/jubatus/jubatus/blob/0.7.0/jubatus/server/common/zk.cpp#L97

**Comment by gintenlabo** [comment]
Fixed via https://github.com/jubatus/jubatus/issues/998.
