### ISSUE TITLE
Bandit: "reset" API returns false before MIX

### ISSUE THREAD

**Issue by rimms** [jubatus/jubatus#994]
The distribution method type of the ``register_reward``  is ``cht``.
So, player_id is not shared to every nodes before MIX.

The distribution method type of the ``reset``  is ``broadcast``. And, its aggregation type is ``all_and`` .

If the number of nodes is 4, servers return ``[true, true, false, false]`` to proxy before MIX. And, proxy returns ``false`` to client.

The Solutions of this problem are followings:
1. Change the aggregation type of ``reset`` to ``all_or``
2. Change the distribution method type of ``register_reward`` to ``broadcast``

I think the former is the better.

**Comment by kmaehashi** [comment]
We decided to go with the former idea.

**Comment by kmaehashi** [comment]
Fixed via #1007
